import 'dart:convert';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:http/http.dart' as http;
import 'package:image_picker/image_picker.dart';
import '../../../../core/errors/exceptions.dart';
import '../models/scanned_food_model.dart';

abstract class FoodScannerRemoteDataSource {
  Future<ScannedFoodModel> analyzeFoodImage(XFile imageFile);
}

class FoodScannerRemoteDataSourceImpl implements FoodScannerRemoteDataSource {
  static String get _apiKey => dotenv.env['GEMINI_API_KEY'] ?? '';

  @override
  Future<ScannedFoodModel> analyzeFoodImage(XFile imageFile) async {
    try {
      if (_apiKey.isEmpty) {
        throw ServerException('API Key is missing in .env');
      }

      final bytes = await imageFile.readAsBytes();
      final base64Image = base64Encode(bytes);

      final uri = Uri.parse(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent',
      );

      const prompt = '''
Analyze this meal photo and provide accurate nutritional estimation.
Output ONLY a raw valid JSON object without markdown fences (no ```json):
{
  "foodName": "Meal Name",
  "calories": 400,
  "protein": 25,
  "carbs": 45,
  "fats": 12,
  "confidenceScore": "95%",
  "detectedIngredients": ["item 1", "item 2"]
}
''';

      final response = await http.post(
        uri,
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': _apiKey,
        },
        body: jsonEncode({
          "contents": [
            {
              "parts": [
                {"text": prompt},
                {
                  "inline_data": {
                    "mime_type": "image/jpeg",
                    "data": base64Image
                  }
                }
              ]
            }
          ]
        }),
      );

      if (response.statusCode == 200) {
        final decoded = jsonDecode(response.body) as Map<String, dynamic>;
        final candidates = decoded['candidates'] as List?;
        if (candidates == null || candidates.isEmpty) {
          throw ServerException('No response generated by AI');
        }

        String rawText = candidates[0]['content']['parts'][0]['text'] as String;
        rawText = rawText.replaceAll('```json', '').replaceAll('```', '').trim();

        final Map<String, dynamic> foodJson = jsonDecode(rawText);
        return ScannedFoodModel.fromJson(foodJson);
      } else {
        throw ServerException('AI Server error: ${response.statusCode} - ${response.body}');
      }
    } catch (e) {
      if (e is ServerException) rethrow;
      throw ServerException('Failed to analyze image: ${e.toString()}');
    }
  }
}